---
version: "2.0"

services:
  web:
    image: avolon42x/www.gieldanowski.ch:release-v0.0.1
    expose:
      - port: 80
        as: 80
        accept:
          - www.gieldanowski.ch
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.2
        memory:
          size: 64Mi
        storage:
          size: 128Mi
  placement:
    dcloud:
      attributes:
        host: akash
        tier: community
      signedBy:
        anyOf: 
        - "akash1nxq8gmsw2vlz3m68qvyvcf3kh6q269ajvqw6y0"
          
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    dcloud:
      profile: web
      count: 1
